package signup;

public class crop {
    private int cropId;
    private String cropName;
    private String cropType;
    private double pricePerUnit;
    private int quantityInStock;

    // Constructors, getters, setters, and other methods as needed

    public crop(int cropId, String cropName, String cropType, double pricePerUnit, int quantityInStock) {
        this.cropId = cropId;
        this.cropName = cropName;
        this.cropType = cropType;
        this.pricePerUnit = pricePerUnit;
        this.quantityInStock = quantityInStock;
    }
    public crop(int cropId, String cropType) {
        this.cropId = cropId;
        this.cropType = cropType;
        // Initialize other fields if necessary
    }
    // Constructor without cropId, assuming it's autogenerated in the database
    public crop(String cropName, String cropType, double pricePerUnit, int quantityInStock) {
        this.cropName = cropName;
        this.cropType = cropType;
        this.pricePerUnit = pricePerUnit;
        this.quantityInStock = quantityInStock;
    }

    public int getCropId() {
        return cropId;
    }

    public void setCropId(int cropId) {
        this.cropId = cropId;
    }

    public String getCropName() {
        return cropName;
    }

    public void setCropName(String cropName) {
        this.cropName = cropName;
    }

    public String getCropType() {
        return cropType;
    }

    public void setCropType(String cropType) {
        this.cropType = cropType;
    }

    public double getPricePerUnit() {
        return pricePerUnit;
    }

    public void setPricePerUnit(double pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }

    public int getQuantityInStock() {
        return quantityInStock;
    }

    public void setQuantityInStock(int quantityInStock) {
        this.quantityInStock = quantityInStock;
    }

    // Other methods, such as toString, equals, etc., can be added based on requirements
}
